{
  "formatVersion": "1.1",
  "component": {
    "group": "com.malinskiy.marathon",
    "module": "base",
    "version": "0.50.4-kolibree",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "5rqox4qe2nglviwvbhck7v5qza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "base-0.50.4-kolibree.jar",
          "url": "base-0.50.4-kolibree.jar",
          "size": 151622,
          "sha512": "a566412941d4ce28ae10bc10470ef5bfefca4eda4bd2117c087380905b181510facffe0d3f76e05598ccaa7a5c9e89d5cd2963e60b90ce71c5d135c7b5b8071e",
          "sha256": "a10b3bcde576db45379aa51b45703b8778cfcf4b87f231b225b867ab1849c034",
          "sha1": "c5528f4f20bfe2fbe57ac99e9c07a2ca8443ce5c",
          "md5": "5eeda7db48940352ff90ed7880469618"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.qameta.allure",
          "module": "allure-java-commons",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "com.linkedin.dextestparser",
          "module": "parser",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.shazam",
          "module": "axmlparser",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "core",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "27.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "base-0.50.4-kolibree.jar",
          "url": "base-0.50.4-kolibree.jar",
          "size": 151622,
          "sha512": "a566412941d4ce28ae10bc10470ef5bfefca4eda4bd2117c087380905b181510facffe0d3f76e05598ccaa7a5c9e89d5cd2963e60b90ce71c5d135c7b5b8071e",
          "sha256": "a10b3bcde576db45379aa51b45703b8778cfcf4b87f231b225b867ab1849c034",
          "sha1": "c5528f4f20bfe2fbe57ac99e9c07a2ca8443ce5c",
          "md5": "5eeda7db48940352ff90ed7880469618"
        }
      ]
    }
  ]
}
