{
  "formatVersion": "1.1",
  "component": {
    "group": "com.malinskiy.marathon",
    "module": "core",
    "version": "0.50.4-kolibree",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "5rqox4qe2nglviwvbhck7v5qza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.koin",
          "module": "koin-core",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.50.4-kolibree.jar",
          "url": "core-0.50.4-kolibree.jar",
          "size": 652287,
          "sha512": "ee3c90dfb923a826b2335e7bd01fa117a03ea88ed052c53ea14e9ed7eb187d363e5e08caa9010080c6931c15f308460de6133654288f11b9a09df97307d9378f",
          "sha256": "0df660cb6f92bfa24f36f7fd0a5e84113eb2920a4e8aaa5f1af3117f3d156ec7",
          "sha1": "250ff8f7e9bd644d6756999504e9caa5ebd39e1f",
          "md5": "af198d5638f77165230e82d9a59aed0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.malinskiy.marathon",
          "module": "html-report",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "execution-timeline",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "io.qameta.allure",
          "module": "allure-java-commons",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.github.automatedowl",
          "module": "allure-environment-writer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "usage",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "ch.frankel.log4k",
          "module": "slf4k-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "org.influxdb",
          "module": "influxdb-java",
          "version": {
            "requires": "2.13"
          }
        },
        {
          "group": "org.koin",
          "module": "koin-core",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.bugsnag",
          "module": "bugsnag",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.50.4-kolibree.jar",
          "url": "core-0.50.4-kolibree.jar",
          "size": 652287,
          "sha512": "ee3c90dfb923a826b2335e7bd01fa117a03ea88ed052c53ea14e9ed7eb187d363e5e08caa9010080c6931c15f308460de6133654288f11b9a09df97307d9378f",
          "sha256": "0df660cb6f92bfa24f36f7fd0a5e84113eb2920a4e8aaa5f1af3117f3d156ec7",
          "sha1": "250ff8f7e9bd644d6756999504e9caa5ebd39e1f",
          "md5": "af198d5638f77165230e82d9a59aed0b"
        }
      ]
    }
  ]
}
