apiVersion: v1
kind: Pod
metadata:
  labels:
    build-pipeline: android
spec:
  containers:
  - name: android-sdk
    image: thyrlian/android-sdk:5.0
    env:
      - name: LANG
        value: "en_US.UTF-8"
      - name: LANGUAGE
        value: "en_US:en"
      - name: LC_ALL
        value: "en_US.UTF-8"
    command:
      - cat
    tty: true
    volumeMounts:
      - name: efs-pvc
        mountPath: /root/.ssh/known_hosts
        subPath: ssh/known_hosts
        readOnly: true
      - name: efs-pvc
        mountPath: /opt/android-sdk
        subPath: android_sdk/
        readOnly: true
    resources:
      requests:
        memory: "24000Mi"
        cpu: "10000m"
      limits:
        memory: "31000Mi"
        cpu: "12000m"
  volumes:
    - name: efs-pvc
      persistentVolumeClaim:
        claimName: pvc-ci
