{
  "formatVersion": "1.1",
  "component": {
    "group": "com.malinskiy.marathon",
    "module": "cli",
    "version": "0.50.4-kolibree",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "5rqox4qe2nglviwvbhck7v5qza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cli-0.50.4-kolibree.jar",
          "url": "cli-0.50.4-kolibree.jar",
          "size": 82381,
          "sha512": "e3864ea0aa5f2c8aface70e12c107543f67d0462be9198e2b38afaaa9531e19c43dc2ce69f217b8346eca1ba5e57bd53900bbe9a66b7b8002330b5365a0ec2c6",
          "sha256": "5a232af11959f1fe2ce7d42cd7fe43dbdf8465bcb327c44b3a1e25aabf0f2674",
          "sha1": "c3e7abcf53452d2d7a4cf28bdd9b39f9c35a3a1c",
          "md5": "d10743c831e44b8fd640fbe9057400ef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.malinskiy.marathon",
          "module": "core",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "vendor-ios",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "base",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "ddmlib",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "usage",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.frankel.log4k",
          "module": "slf4k-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.xenomachina",
          "module": "kotlin-argparser",
          "version": {
            "requires": "2.0.7"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.4.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "cli-0.50.4-kolibree.jar",
          "url": "cli-0.50.4-kolibree.jar",
          "size": 82381,
          "sha512": "e3864ea0aa5f2c8aface70e12c107543f67d0462be9198e2b38afaaa9531e19c43dc2ce69f217b8346eca1ba5e57bd53900bbe9a66b7b8002330b5365a0ec2c6",
          "sha256": "5a232af11959f1fe2ce7d42cd7fe43dbdf8465bcb327c44b3a1e25aabf0f2674",
          "sha1": "c3e7abcf53452d2d7a4cf28bdd9b39f9c35a3a1c",
          "md5": "d10743c831e44b8fd640fbe9057400ef"
        }
      ]
    }
  ]
}
