{
  "formatVersion": "1.1",
  "component": {
    "group": "com.malinskiy.marathon",
    "module": "html-report",
    "version": "0.50.4-kolibree",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "5rqox4qe2nglviwvbhck7v5qza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "html-report-0.50.4-kolibree.jar",
          "url": "html-report-0.50.4-kolibree.jar",
          "size": 104047,
          "sha512": "399a60b02cf8ba86669c5c8645a019d59c57b4e5783bf39e59273f55f6378020f9b961538e85ad3459dbe0401495cd2cd94c6f08e2d9e9d91263b15bc64ee657",
          "sha256": "f541ab331e233d6e57faf172cb6969ebeeb2ee035d5725e39383236dce038de3",
          "sha1": "5bdf7c5ecb19d7603fe515f965b1d3bb4a76a2a6",
          "md5": "d98f0954cae694eb1c89574cfa14254d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.4.9"
          }
        }
      ],
      "files": [
        {
          "name": "html-report-0.50.4-kolibree.jar",
          "url": "html-report-0.50.4-kolibree.jar",
          "size": 104047,
          "sha512": "399a60b02cf8ba86669c5c8645a019d59c57b4e5783bf39e59273f55f6378020f9b961538e85ad3459dbe0401495cd2cd94c6f08e2d9e9d91263b15bc64ee657",
          "sha256": "f541ab331e233d6e57faf172cb6969ebeeb2ee035d5725e39383236dce038de3",
          "sha1": "5bdf7c5ecb19d7603fe515f965b1d3bb4a76a2a6",
          "md5": "d98f0954cae694eb1c89574cfa14254d"
        }
      ]
    }
  ]
}
