{
  "formatVersion": "1.1",
  "component": {
    "group": "com.malinskiy.marathon",
    "module": "usage",
    "version": "0.50.4-kolibree",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "5rqox4qe2nglviwvbhck7v5qza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "usage-0.50.4-kolibree.jar",
          "url": "usage-0.50.4-kolibree.jar",
          "size": 9640,
          "sha512": "a73950e41da15387222af1db0c7996f1971759f1a2666e66b045224573b893100a1b131e8318e9f08fcfc9f3b7a69ef659f9987871eaaf86eef16d515366cbd5",
          "sha256": "7b8a6910b33c23f673ef0d4d47751d042b2cc3c06ee7aac122a262e713ee749c",
          "sha1": "b309c2c03ab2ce15d2cb1db39f958e96b2bd7c3a",
          "md5": "6587aa71e6a19be477c6c5a3201d827d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.brsanthu",
          "module": "google-analytics-java",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "usage-0.50.4-kolibree.jar",
          "url": "usage-0.50.4-kolibree.jar",
          "size": 9640,
          "sha512": "a73950e41da15387222af1db0c7996f1971759f1a2666e66b045224573b893100a1b131e8318e9f08fcfc9f3b7a69ef659f9987871eaaf86eef16d515366cbd5",
          "sha256": "7b8a6910b33c23f673ef0d4d47751d042b2cc3c06ee7aac122a262e713ee749c",
          "sha1": "b309c2c03ab2ce15d2cb1db39f958e96b2bd7c3a",
          "md5": "6587aa71e6a19be477c6c5a3201d827d"
        }
      ]
    }
  ]
}
