{
  "formatVersion": "1.1",
  "component": {
    "group": "com.malinskiy.marathon",
    "module": "vendor-ios",
    "version": "0.50.4-kolibree",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "5rqox4qe2nglviwvbhck7v5qza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "vendor-ios-0.50.4-kolibree.jar",
          "url": "vendor-ios-0.50.4-kolibree.jar",
          "size": 233455,
          "sha512": "a65ea37c5b8f6712362d458ec0fbe6ba6f91a2902c43156be2673297968ba56439865a003a0fb4d84d114bcf1ef852159bd2803a04d6f2a281620c63812f07ee",
          "sha256": "eb25d9187004c461cf2ba7a8fb49d4c1e52504ac55ee726bbe18e1d511ce12de",
          "sha1": "b1f27d6d1dc88bd77e6a78750b89c99ad1eb2f1f",
          "md5": "e0f052932540375e2dcaf56628544611"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "ch.frankel.log4k",
          "module": "slf4k-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        },
        {
          "group": "com.googlecode.plist",
          "module": "dd-plist",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "26.0-jre"
          }
        },
        {
          "group": "com.github.fracpete",
          "module": "rsync4j-all",
          "version": {
            "requires": "3.1.2-12"
          }
        },
        {
          "group": "com.hierynomus",
          "module": "sshj",
          "version": {
            "requires": "0.26.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.9.4.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "core",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.3"
          }
        }
      ],
      "files": [
        {
          "name": "vendor-ios-0.50.4-kolibree.jar",
          "url": "vendor-ios-0.50.4-kolibree.jar",
          "size": 233455,
          "sha512": "a65ea37c5b8f6712362d458ec0fbe6ba6f91a2902c43156be2673297968ba56439865a003a0fb4d84d114bcf1ef852159bd2803a04d6f2a281620c63812f07ee",
          "sha256": "eb25d9187004c461cf2ba7a8fb49d4c1e52504ac55ee726bbe18e1d511ce12de",
          "sha1": "b1f27d6d1dc88bd77e6a78750b89c99ad1eb2f1f",
          "md5": "e0f052932540375e2dcaf56628544611"
        }
      ]
    }
  ]
}
