{
  "formatVersion": "1.1",
  "component": {
    "group": "com.malinskiy.marathon",
    "module": "ddmlib",
    "version": "0.50.4-kolibree",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "5rqox4qe2nglviwvbhck7v5qza"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ddmlib-0.50.4-kolibree.jar",
          "url": "ddmlib-0.50.4-kolibree.jar",
          "size": 88749,
          "sha512": "58f152b3c995202f2783cfd1cbc4bae5e6b038ad5a5d4d9b61722ed9a4176772f7646333a8c18c9d7dbf5367e11d5eeeb0b60441140f498f8bce04123776eec9",
          "sha256": "abc73f03e5725127410de227665e9ef67f23318fd88bdc351ca02010cb2fcb7f",
          "sha1": "5859e53af23a8dd9d8d6bd4f4acb68ce3cf7a636",
          "md5": "faf57de2f481bf0d6d20dae8dc0e0c1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        },
        {
          "group": "io.qameta.allure",
          "module": "allure-java-commons",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging",
          "version": {
            "requires": "1.4.9"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "27.1.0"
          }
        },
        {
          "group": "com.linkedin.dextestparser",
          "module": "parser",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.shazam",
          "module": "axmlparser",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.9.5"
          }
        },
        {
          "group": "org.imgscalr",
          "module": "imgscalr-lib",
          "version": {
            "requires": "4.2"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "core",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "com.malinskiy.marathon",
          "module": "base",
          "version": {
            "requires": "0.50.4-kolibree"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ddmlib-0.50.4-kolibree.jar",
          "url": "ddmlib-0.50.4-kolibree.jar",
          "size": 88749,
          "sha512": "58f152b3c995202f2783cfd1cbc4bae5e6b038ad5a5d4d9b61722ed9a4176772f7646333a8c18c9d7dbf5367e11d5eeeb0b60441140f498f8bce04123776eec9",
          "sha256": "abc73f03e5725127410de227665e9ef67f23318fd88bdc351ca02010cb2fcb7f",
          "sha1": "5859e53af23a8dd9d8d6bd4f4acb68ce3cf7a636",
          "md5": "faf57de2f481bf0d6d20dae8dc0e0c1e"
        }
      ]
    }
  ]
}
